#!/bin/bash

repo=$1
pass=$2
svndir=/var/lib/svn
repodir="${svndir}/$1"

if [[ -d "$repodir" ]]; then
    echo "$repodir already exists"
    exit
fi

cd "$svndir"
svnadmin create "$repo"

echo "$pass" | sudo -S chmod 777 -R "$repo"
echo "$pass" | sudo -S chown -R www-data:www-data "$repo"
