#!/usr/bin/env python3

import os
import sys
import argparse

parser = argparse.ArgumentParser(prog='useradd',description='create new user')
parser.add_argument('-s', '--shell')
parser.add_argument('-m', '--create-home')
parser.add_argument('-r', '--real-name')
parser.add_argument('-G', '--groups')
parser.add_argument('-p', '--password')
parser.add_argument('-U', '--uid')
parser.add_argument('LOGIN', metavar='N', type=str)

args = parser.parse_args()


print(args)
